apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ahx2blj22-go 
  janus-idp.io/tekton: ahx2blj22-go
  backstage.io/kubernetes-id: ahx2blj22-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ahx2blj22-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  